name:                mredact
version:             0.1.0.0
github:              mikaunix/mredact
license:             BSD3
author:              Mikaël Dusenne
maintainer:          mikaunix@gmail.com

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            all

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/mikaunix/mredact#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - hlib
    - process
    - regex-pcre
    - pandoc
    - pandoc-types
    - skylighting
    - random
    - containers
    - directory
    - regex-compat

executables:
  mredact:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mredact
    - hlib
    - process
    - regex-pcre
    - pandoc
    - pandoc-types
    - skylighting
    - random
    - containers
    - directory
    - regex-compat
    - mime
    - base64-bytestring
    - lens
    
tests:
  mredact-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mredact
